/* 
 * OpenHack
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Answer submitted for the trivia API
    /// </summary>
    [DataContract]
    public partial class AnswerModel :  IEquatable<AnswerModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnswerModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AnswerModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AnswerModel" /> class.
        /// </summary>
        /// <param name="UserId">Azure AD Object Id for the user submitting the answer (required).</param>
        /// <param name="QuestionId">Id of the Question being answered (required).</param>
        /// <param name="AnswerId">Id of the Question Option proposed as the answer (required).</param>
        public AnswerModel(Guid? UserId = default(Guid?), int? QuestionId = default(int?), int? AnswerId = default(int?))
        {
            // to ensure "UserId" is required (not null)
            if (UserId == null)
            {
                throw new InvalidDataException("UserId is a required property for AnswerModel and cannot be null");
            }
            else
            {
                this.UserId = UserId;
            }
            // to ensure "QuestionId" is required (not null)
            if (QuestionId == null)
            {
                throw new InvalidDataException("QuestionId is a required property for AnswerModel and cannot be null");
            }
            else
            {
                this.QuestionId = QuestionId;
            }
            // to ensure "AnswerId" is required (not null)
            if (AnswerId == null)
            {
                throw new InvalidDataException("AnswerId is a required property for AnswerModel and cannot be null");
            }
            else
            {
                this.AnswerId = AnswerId;
            }
        }
        
        /// <summary>
        /// Azure AD Object Id for the user submitting the answer
        /// </summary>
        /// <value>Azure AD Object Id for the user submitting the answer</value>
        [DataMember(Name="userId", EmitDefaultValue=false)]
        public Guid? UserId { get; set; }

        /// <summary>
        /// Id of the Question being answered
        /// </summary>
        /// <value>Id of the Question being answered</value>
        [DataMember(Name="questionId", EmitDefaultValue=false)]
        public int? QuestionId { get; set; }

        /// <summary>
        /// Id of the Question Option proposed as the answer
        /// </summary>
        /// <value>Id of the Question Option proposed as the answer</value>
        [DataMember(Name="answerId", EmitDefaultValue=false)]
        public int? AnswerId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AnswerModel {\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  QuestionId: ").Append(QuestionId).Append("\n");
            sb.Append("  AnswerId: ").Append(AnswerId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AnswerModel);
        }

        /// <summary>
        /// Returns true if AnswerModel instances are equal
        /// </summary>
        /// <param name="input">Instance of AnswerModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AnswerModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.QuestionId == input.QuestionId ||
                    (this.QuestionId != null &&
                    this.QuestionId.Equals(input.QuestionId))
                ) && 
                (
                    this.AnswerId == input.AnswerId ||
                    (this.AnswerId != null &&
                    this.AnswerId.Equals(input.AnswerId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UserId != null)
                    hashCode = hashCode * 59 + this.UserId.GetHashCode();
                if (this.QuestionId != null)
                    hashCode = hashCode * 59 + this.QuestionId.GetHashCode();
                if (this.AnswerId != null)
                    hashCode = hashCode * 59 + this.AnswerId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
