/* 
 * OpenHack
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Question option (possible answer) for question in Trivia API
    /// </summary>
    [DataContract]
    public partial class QuestionOptionModel :  IEquatable<QuestionOptionModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QuestionOptionModel" /> class.
        /// </summary>
        /// <param name="Id">Question Option Id.</param>
        /// <param name="Text">Question option text.</param>
        public QuestionOptionModel(int? Id = default(int?), string Text = default(string))
        {
            this.Id = Id;
            this.Text = Text;
        }
        
        /// <summary>
        /// Question Option Id
        /// </summary>
        /// <value>Question Option Id</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Question option text
        /// </summary>
        /// <value>Question option text</value>
        [DataMember(Name="text", EmitDefaultValue=false)]
        public string Text { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return Text;
            
            //var sb = new StringBuilder();
            //sb.Append("class QuestionOptionModel {\n");
            //sb.Append("  Id: ").Append(Id).Append("\n");
            //sb.Append("  Text: ").Append(Text).Append("\n");
            //sb.Append("}\n");
            //return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as QuestionOptionModel);
        }

        /// <summary>
        /// Returns true if QuestionOptionModel instances are equal
        /// </summary>
        /// <param name="input">Instance of QuestionOptionModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QuestionOptionModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Text != null)
                    hashCode = hashCode * 59 + this.Text.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
